runtime: python27
api_version: 1
threadsafe: yes
version: 1

handlers:
- url: /js
  static_dir: static/js
- url: /pdfjs
  static_dir: static/pdfjs
- url: /files
  static_dir: files

- url: /styles
  static_dir: static/styles

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:
- ^node_modules/.*$
- ^(.*/)?.*\.py[co]$