runtime: python27
api_version: 1
threadsafe: yes
version: 1

handlers:
- url: /js
  static_dir: static/dist/js

- url: /files
  static_dir: files


# site root
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:
- ^node_modules/.*$
- ^bower_components/.*$
- ^PyPDF2-repo/.*$

- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.DS_Store$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
